### ISSUE TITLE
Patch Suggestion

### ISSUE THREAD

**Issue by r-lyeh** [nfrechette/acl-ue4-plugin#13]
First of all, great work in ACL. 
Hope it gets integrated in main codebase someday :o)

Now a suggestion, as I just stumbled upon this: 

https://coderwall.com/p/6aw72a/creating-patch-from-github-pull-request

Ie, if you flatten all your commits in the 4.19 branch, then users could download & apply the patch from your single commit without cloning the whole repo itself (which is large enough).

**Comment by nfrechette** [comment]
That's a good idea but I think it would require a separate branch in my UE fork for it. I do want to keep the commit history but I agree that a branch with a single commit for easy patching makes sense.
I'll see what I can do when I get around to it but I'm also unsure how much support to offer pre-4.23 engines since so far things are on track for the plugin to be natively supported by that version. Surely game teams will use earlier versions for some years but I haven't decided yet if I would maintain both pre/post 4.23 plugins in parallel.

For similar reasons, I haven't gotten around to creating 4.20/4.21/4.22 branches yet.

**Comment by nfrechette** [comment]
Fixed by #15 
I will be updating the stats with UE 4.22.2 and release a new version of the plugin soon for it. Branch and patch links have been added.
Thanks again for the suggestion!

**Comment by nfrechette** [comment]
@all-contributors add @r-lyeh as documentation
