### ISSUE TITLE
AnimationCompressionLibraryDatabase should not be loaded in the beginning if the visual fidelity is lowest. 

### ISSUE THREAD

**Issue by NoahZuo** [nfrechette/acl-ue4-plugin#84]
Since high importance tier is stored inside the animation clip.  if the database visual fidelity is lowest, the database should not be loaded into memory in the beginning. But it still shows up in the memreport: 

![image](https://user-images.githubusercontent.com/10735147/119472093-816e0e80-bd7c-11eb-8624-f1dac66d2b58.png)

But actually it is loaded into memory because the Database asset is a hard pointer: 

![image](https://user-images.githubusercontent.com/10735147/119471579-ff7de580-bd7b-11eb-9208-b75d74750c72.png)

As a result, this would cause database being loaded into the memory. 

I've use obj ref for the database, and get this result: 
![image](https://user-images.githubusercontent.com/10735147/119472693-078a5500-bd7d-11eb-9889-5d3c96d6e443.png)

Would a `TAssetPtr` be better for this?

**Comment by nfrechette** [comment]
The database is always present in some form, but the bulk data is loaded on demand. As such, it is normal for the asset to always be present in memory. It also contains all the anim sequence data itself, it no longer lives in the anim sequence objects. This complicates reporting a bit and is why the current report isn't accurate if you skip the assert. Once #82 is fixed, the memreport should be accurate and reflect the above.

Because there is no way to strip the data from the anim sequence during cooking, it is done after compression and the data is stored separately in the codec specific data for the anim sequence. During cook, we have control over this and the data is stripped from the anim sequence. When the database is built, the anim sequence data is transformed to move part of it in the database to make it streamable (or to strip it if you request it). When the anim sequence loads, we lookup in the database asset where the data lives and we setup an array view into it.

I'll leave this issue open for now but I expect it will be resolved once #82 is fixed.

**Comment by nfrechette** [comment]
Should be fixed by #86
